spring:
  application:
    name: blog # 应用名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    name: defaultDataSource # 数据源名称
    url: jdbc:mysql://localhost:3306/api?serverTimezone=UTC # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库密码：

server:
  port: 8081 # 应用服务 WEB 访问端口

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志
  global-config:
    db-config:
      table-prefix: ms_ # 数据库表前缀
